### ISSUE TITLE
Compilation error in spring example

### ISSUE THREAD

**Issue by berndvarga** [camunda/camunda-platform-get-started#138] opened 2022-09-05 15:06 UTC
I get following error during the compilation of the spring example.
I switched back to the usage of 8.0.4, which works without issue.

`
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/docker/camunda/camunda-platform-get-started/spring/src/main/java/io/camunda/getstarted/ProcessApplication.java:[4,38] cannot find symbol
  symbol:   class ZeebeClientLifecycle
  location: package io.camunda.zeebe.spring.client
[ERROR] /home/docker/camunda/camunda-platform-get-started/spring/src/main/java/io/camunda/getstarted/ProcessApplication.java:[27,11] cannot find symbol
  symbol:   class ZeebeClientLifecycle
  location: class io.camunda.getstarted.ProcessApplication
`

**Comment by menski** [comment] 2022-10-11 14:36
Thanks for reporting, as a duplicate of #132 it was closed by the fix in https://github.com/camunda/camunda-platform-get-started/commit/5e4727e6a68b258e61b112a5d65e3ef956dc886f.

**Closed by menski** 2022-10-11 14:36 UTC
